# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='priceType',
            field=models.IntegerField(choices=[(1, 'Fare'), (2, 'Price')]),
        ),
        migrations.AlterField(
            model_name='providers',
            name='ratetype',
            field=models.IntegerField(choices=[(2, 'numbers'), (1, 'stars')]),
        ),
    ]
