# Generated by Django 3.2.9 on 2021-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211130_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='priceType',
            field=models.CharField(choices=[(1, 'Fare'), (2, 'Price')], max_length=100),
        ),
        migrations.AlterField(
            model_name='providers',
            name='ratetype',
            field=models.IntegerField(choices=[(1, 'stars'), (2, 'numbers')]),
        ),
        migrations.AlterField(
            model_name='providers',
            name='seprately',
            field=models.IntegerField(choices=[(2, 'comma'), (1, 'Array Of String')]),
        ),
    ]
