# Generated by Django 3.2.9 on 2021-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20211130_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='priceType',
            field=models.CharField(choices=[('Price', '2'), ('Fare', '1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='providers',
            name='ratetype',
            field=models.IntegerField(choices=[(2, 'numbers'), (1, 'stars')]),
        ),
        migrations.AlterField(
            model_name='providers',
            name='seprately',
            field=models.IntegerField(choices=[(1, 'Array Of String'), (2, 'comma')]),
        ),
    ]
