# Generated by Django 3.2.9 on 2021-11-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20211130_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='providerHotelKey',
            field=models.IntegerField(choices=[(1, 'hotal'), (2, 'hotelname')], null=True),
        ),
        migrations.AlterField(
            model_name='providers',
            name='priceType',
            field=models.CharField(choices=[('1', 'Fare'), ('2', 'Price')], max_length=100),
        ),
    ]
