# Generated by Django 3.2.9 on 2021-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20211130_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities', to='apis.amenities'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='priceType',
            field=models.CharField(choices=[('2', 'Price'), ('1', 'Fare')], max_length=100),
        ),
        migrations.AlterField(
            model_name='providers',
            name='seprately',
            field=models.IntegerField(choices=[(2, 'comma'), (1, 'Array Of String')]),
        ),
    ]
